return {
    -- settings = {
    --     modkey = "Mod4",
    --     monitors = {
    --         left = 1,
    --         center = 2,
    --         right = 3,
    --     },
    -- },
    -- theme = {
    --     name = "lynxburn2",
    -- },
    -- widgets = {
    --     order = {
    --         "network",
    --         "audio",
    --         "notify",
    --     },
    --     modules = {
    --         network = {
    --             enabled = true,
    --             -- cycle = false,
    --         },
    --     },
    -- },
    -- commands = {
    --     terminal = "alacritty",
    --     autostart_once = {
    --         "nm-applet --sm-disable",
    --     },
    -- },
}
