local M = {}

function M.build(opts)
    local fonts = opts.fonts or {}
    local theme_dir = opts.theme_dir
    local zenburn_dir = opts.zenburn_dir
    local padding = 2

    return {
        dir = theme_dir,
        wallpaper = os.getenv("HOME") .. "/.wallpaper",

        font = fonts.base or "Hack Nerd Font Mono 9",
        border_width = 1,
        useless_gap = 5,

        wibar_height = 20,
        wibar_position = "top",
        space = " ",
        systray_icon_spacing = padding,
        widget_padding_top = padding,
        widget_padding_bottom = padding,
        widget_padding_left = padding,
        widget_padding_right = padding,

        tasklist_plain_task_name = true,
        tasklist_disable_icon = false,
        taglist_squares_sel = theme_dir .. "/icons/square_sel.png",
        taglist_squares_unsel = theme_dir .. "/icons/square_unsel.png",

        notification_icon_size = 50,
        notification_border_width = 1,
        notification_max_width = 500,

        titlebar_close_button_normal = zenburn_dir .. "/titlebar/close_normal.png",
        titlebar_close_button_focus = zenburn_dir .. "/titlebar/close_focus.png",
        titlebar_ontop_button_normal_inactive = zenburn_dir .. "/titlebar/ontop_normal_inactive.png",
        titlebar_ontop_button_focus_inactive = zenburn_dir .. "/titlebar/ontop_focus_inactive.png",
        titlebar_ontop_button_normal_active = zenburn_dir .. "/titlebar/ontop_normal_active.png",
        titlebar_ontop_button_focus_active = zenburn_dir .. "/titlebar/ontop_focus_active.png",
        titlebar_sticky_button_normal_inactive = zenburn_dir .. "/titlebar/sticky_normal_inactive.png",
        titlebar_sticky_button_focus_inactive = zenburn_dir .. "/titlebar/sticky_focus_inactive.png",
        titlebar_sticky_button_normal_active = zenburn_dir .. "/titlebar/sticky_normal_active.png",
        titlebar_sticky_button_focus_active = zenburn_dir .. "/titlebar/sticky_focus_active.png",
        titlebar_floating_button_normal_inactive = zenburn_dir .. "/titlebar/floating_normal_inactive.png",
        titlebar_floating_button_focus_inactive = zenburn_dir .. "/titlebar/floating_focus_inactive.png",
        titlebar_floating_button_normal_active = zenburn_dir .. "/titlebar/floating_normal_active.png",
        titlebar_floating_button_focus_active = zenburn_dir .. "/titlebar/floating_focus_active.png",
        titlebar_maximized_button_normal_inactive = zenburn_dir .. "/titlebar/maximized_normal_inactive.png",
        titlebar_maximized_button_focus_inactive = zenburn_dir .. "/titlebar/maximized_focus_inactive.png",
        titlebar_maximized_button_normal_active = zenburn_dir .. "/titlebar/maximized_normal_active.png",
        titlebar_maximized_button_focus_active = zenburn_dir .. "/titlebar/maximized_focus_active.png",

        icon_mail = theme_dir .. "/icons/mail.png",
        icon_cpu = theme_dir .. "/icons/cpu.png",
        icon_sysload = theme_dir .. "/icons/cpu.png",
        icon_mem = theme_dir .. "/icons/mem.png",
        icon_fs = theme_dir .. "/icons/hdd.png",
        icon_powermenu = theme_dir .. "/icons/cpu.png",

        layout_txt_fairv = "vertical",
        layout_txt_fairh = "horizontal",
        layout_txt_centerwork = "centered",
        layout_txt_centerworkh = "centerh",
        layout_txt_floating = "floating",

        lxmedia_hover_close_poll_interval = 0.25,
        lxmedia_hover_close_timeout = 2,
        lxmedia_osd_timeout = 1,
        lxmedia_popup_placement_media = "center",
        lxmedia_popup_placement_devices = "side",
        lxmedia_popup_width_media = 360,
        lxmedia_popup_width_devices = 360,
        lxmedia_artwork_width = 420,
        lxmedia_artwork_max_height = 680,
        lxmedia_icon_volume = "",
        lxmedia_icon_muted = "",
        lxmedia_icon_brightness = "󰃠",
        lxmedia_icon_mic_active = "🎙",
        lxmedia_icon_mic_muted = "×",
        lxmedia_icon_font = fonts.icon_very_large or fonts.base,
        lxmedia_icon_width = 22,
        lxmedia_bar_padding = 2,
        lxmedia_bar_hover_open_delay = 0.5,

        lxnotify_icon_suspended = "󰂛",
        lxnotify_icon_idle = "󰂚",
        lxnotify_icon_width = 26,
        lxnotify_widget_font = fonts.notify_widget or fonts.base,
        lxnotify_popup_width = 360,
        lxnotify_popup_placement = "side",
        lxnotify_notification_icon_size = 32,
        lxnotify_group_icon_size = 20,

        lxdisplay_icon = "󰃟",
        lxdisplay_icon_night = "󰖔",
        lxdisplay_icon_brightness = "󰃠",
        lxdisplay_icon_font = fonts.icon or fonts.base,
        lxdisplay_icon_width = 24,
        lxdisplay_bar_width = 50,
        lxdisplay_bar_height = 8,
        lxdisplay_bar_spacing = 6,
        lxdisplay_bar_padding = 2,
        lxdisplay_bar_end_margin = 4,
        lxdisplay_bar_hover_open_delay = 0.5,
        lxdisplay_popup_width = 380,
        lxdisplay_popup_placement = "center",
        lxdisplay_osd_width = 260,
        lxdisplay_osd_height = 18,
        lxdisplay_osd_margin = 16,
        lxdisplay_osd_timeout = 1,

        lxbluetooth_icon = "",
        lxbluetooth_popup_placement = "side",
        lxbluetooth_icon_width = 24,
        lxbluetooth_popup_width = 360,

        lxnetwork_icon = "",
        lxnetwork_icon_disabled = "󰖪",
        lxnetwork_popup_placement = "side",
        lxnetwork_popup_width = 360,
        lxnetwork_icon_font = fonts.icon_very_large or fonts.base,
        lxnetwork_icon_width = 32,

        lxpower_icon_ac = "",
        lxpower_icon_battery = "",
        lxpower_popup_placement = "center",
        lxpower_popup_width = 360,
        lxpower_icon_pinned = "",
        lxpower_icon_font = fonts.icon_large or fonts.base,
        lxpower_icon_width = 26,

        lxsecrets_icon = "",
        lxsecrets_icon_font = fonts.icon or fonts.base,
        lxsecrets_icon_width = 24,
        lxsecrets_popup_width = 380,
        lxsecrets_popup_placement = "side",

        lxrunner_border_width = 1,
        lxrunner_cursor = "_",
        lxrunner_input_font = fonts.base or "Hack Nerd Font Mono 9",
        lxrunner_radius = 6,
        lxrunner_outer_margin = 10,
        lxrunner_padding = 12,
        lxrunner_row_font = fonts.base or "Hack Nerd Font Mono 9",
        lxrunner_row_padding = 10,
        lxrunner_icon_font = fonts.base or "Hack Nerd Font Mono 9",
        lxrunner_icon_size = 14,
        lxrunner_icon_text_spacing = 8,
    }
end

return M
