local M = {
    order = {
        "toggle_quake",
        "jump_to_urgent_client",
        "restore_minimized",
        "cycle_focus",
        "cycle_focus_previous",
        "swap_right",
        "swap_left",
        "swap_up",
        "swap_down",
        "focus_down",
        "focus_up",
        "focus_left",
        "focus_right",
        "view_previous_tag",
        "view_next_tag",
        "restore_tag_history",
        "next_layout",
        "prev_layout",
        "grow_gaps",
        "shrink_gaps",
        "show_media_popup",
        "show_notification_popup",
        "show_bluetooth_popup",
        "show_network_popup",
        "show_power_popup",
        "show_calendar",
        "toggle_lxrunner",
        "open_launcher",
        "open_terminal",
        "open_file_browser",
        "screenshot_region",
        "screenshot_desktop",
        "screenshot_window",
        "start_awesome_on_tv",
        "lock_screen",
        "media_play_pause",
        "media_next",
        "media_prev",
        "volume_up",
        "volume_down",
        "toggle_mute",
        "brightness_up",
        "brightness_down",
        "brightness_off",
        "show_help",
        "reload_awesome",
        "quit_awesome",
        "toggle_notifications",
        "kill_client",
        "toggle_floating",
        "move_to_screen",
        "move_to_left_screen",
        "move_to_right_screen",
        "toggle_titlebar",
        "minimize_client",
        "maximize_client",
    },
    toggle_quake = {
        scope = "global",
        modifiers = { "modkey" },
        key = "dead_circumflex",
        on_press = "toggle_quake",
        description = "quake terminal",
        group = "04. commands",
    },
    jump_to_urgent_client = {
        scope = "global",
        modifiers = { "modkey" },
        key = "u",
        on_press = "jump_to_urgent_client",
        description = "jump to urgent client",
        group = "01. window",
    },
    restore_minimized = {
        scope = "global",
        modifiers = { "modkey", "ctrlkey" },
        key = "n",
        on_press = "restore_minimized",
        description = "restore minimized program",
        group = "01. window",
    },
    cycle_focus = {
        scope = "global",
        modifiers = { "modkey" },
        key = "Tab",
        on_press = "cycle_focus",
        description = "focus next by index",
        group = "01. window",
    },
    cycle_focus_previous = {
        scope = "global",
        modifiers = { "modkey", "shiftkey" },
        key = "Tab",
        on_press = "cycle_focus",
        description = "focus previous by index",
        group = "01. window",
    },
    swap_right = {
        scope = "global",
        modifiers = { "modkey", "ctrlkey" },
        key = "Right",
        on_press = "swap_right",
        description = "swap with left client",
        group = "01. window",
    },
    swap_left = {
        scope = "global",
        modifiers = { "modkey", "ctrlkey" },
        key = "Left",
        on_press = "swap_left",
        description = "swap with right client",
        group = "01. window",
    },
    swap_up = {
        scope = "global",
        modifiers = { "modkey", "ctrlkey" },
        key = "Up",
        on_press = "swap_up",
        description = "swap with upper client",
        group = "01. window",
    },
    swap_down = {
        scope = "global",
        modifiers = { "modkey", "ctrlkey" },
        key = "Down",
        on_press = "swap_down",
        description = "swap with lower client",
        group = "01. window",
    },
    focus_down = {
        scope = "global",
        modifiers = { "modkey" },
        key = "Down",
        on_press = "focus_down",
        description = "focus down",
        group = "01. window",
    },
    focus_up = {
        scope = "global",
        modifiers = { "modkey" },
        key = "Up",
        on_press = "focus_up",
        description = "focus up",
        group = "01. window",
    },
    focus_left = {
        scope = "global",
        modifiers = { "modkey" },
        key = "Left",
        on_press = "focus_left",
        description = "focus left",
        group = "01. window",
    },
    focus_right = {
        scope = "global",
        modifiers = { "modkey" },
        key = "Right",
        on_press = "focus_right",
        description = "focus right",
        group = "01. window",
    },
    view_previous_tag = {
        scope = "global",
        modifiers = { "altkey", "ctrlkey" },
        key = "Left",
        on_press = "view_previous_tag",
        description = "view previous",
        group = "02. desktop",
    },
    view_next_tag = {
        scope = "global",
        modifiers = { "altkey", "ctrlkey" },
        key = "Right",
        on_press = "view_next_tag",
        description = "view next",
        group = "02. desktop",
    },
    restore_tag_history = {
        scope = "global",
        modifiers = { "modkey", "altkey" },
        key = "Escape",
        on_press = "restore_tag_history",
        description = "go back",
        group = "02. desktop",
    },
    next_layout = {
        scope = "global",
        modifiers = { "modkey" },
        key = "space",
        on_press = "next_layout",
        description = "select next layout",
        group = "03. layout",
    },
    prev_layout = {
        scope = "global",
        modifiers = { "modkey", "shiftkey" },
        key = "space",
        on_press = "prev_layout",
        description = "select prev layout",
        group = "03. layout",
    },
    grow_gaps = {
        scope = "global",
        modifiers = { "modkey", "ctrlkey" },
        key = "+",
        on_press = "grow_gaps",
        description = "increment useless gaps",
        group = "03. layout",
    },
    shrink_gaps = {
        scope = "global",
        modifiers = { "modkey", "ctrlkey" },
        key = "-",
        on_press = "shrink_gaps",
        description = "decrement useless gaps",
        group = "03. layout",
    },
    show_media_popup = {
        scope = "global",
        modifiers = { "modkey" },
        key = "Prior",
        on_press = "show_media_popup",
        description = "show media popup",
        group = "04. commands",
    },
    show_notification_popup = {
        scope = "global",
        modifiers = { "modkey" },
        key = "Next",
        on_press = "show_notification_popup",
        description = "show notification popup",
        group = "04. commands",
    },
    show_bluetooth_popup = {
        scope = "global",
        modifiers = { "modkey" },
        key = "F10",
        on_press = "show_bluetooth_popup",
        description = "show bluetooth popup",
        group = "04. commands",
    },
    show_network_popup = {
        scope = "global",
        modifiers = { "modkey" },
        key = "F11",
        on_press = "show_network_popup",
        description = "show network popup",
        group = "04. commands",
    },
    show_power_popup = {
        scope = "global",
        modifiers = { "modkey" },
        key = "F12",
        on_press = "show_power_popup",
        description = "show power popup",
        group = "04. commands",
    },
    show_calendar = {
        scope = "global",
        modifiers = { "modkey" },
        key = "c",
        on_press = "show_calendar",
        description = "show calendar",
        group = "04. commands",
    },
    toggle_lxrunner = {
        scope = "global",
        modifiers = { "altkey" },
        key = "F2",
        on_press = "toggle_lxrunner",
        description = "lxrunner",
        group = "04. commands",
    },
    open_launcher = {
        scope = "global",
        modifiers = { "altkey" },
        key = "F3",
        on_press = "open_launcher",
        description = "launcher",
        group = "04. commands",
    },
    open_terminal = {
        scope = "global",
        modifiers = { "modkey" },
        key = "q",
        on_press = "open_terminal",
        description = "terminal",
        group = "04. commands",
    },
    open_file_browser = {
        scope = "global",
        modifiers = { "modkey" },
        key = "e",
        on_press = "open_file_browser",
        description = "file browser",
        group = "04. commands",
    },
    screenshot_region = {
        scope = "global",
        modifiers = { "modkey" },
        key = "p",
        on_press = "screenshot_region",
        description = "screenshot of region",
        group = "04. commands",
    },
    screenshot_desktop = {
        scope = "global",
        modifiers = { "altkey", "ctrlkey" },
        key = "p",
        on_press = "screenshot_desktop",
        description = "screenshot of desktop",
        group = "04. commands",
    },
    screenshot_window = {
        scope = "global",
        modifiers = { "modkey", "ctrlkey" },
        key = "p",
        on_press = "screenshot_window",
        description = "screenshot of window",
        group = "04. commands",
    },
    start_awesome_on_tv = {
        scope = "global",
        modifiers = { "modkey", "altkey" },
        key = "t",
        on_press = "start_awesome_on_tv",
        description = "start awesome on TV",
        group = "04. commands",
    },
    lock_screen = {
        {
            scope = "global",
            modifiers = { "altkey", "ctrlkey" },
            key = "l",
            on_press = "lock_screen",
            description = "lock screen",
            group = "04. commands",
        },
        {
            scope = "global",
            modifiers = { "modkey", "altkey" },
            key = "F12",
            on_press = "lock_screen",
            description = "lock screen",
            group = "04. commands",
        },
        {
            scope = "global",
            modifiers = { "modkey", "altkey", "ctrlkey" },
            key = "Delete",
            on_press = "lock_screen",
            description = "lock screen",
            group = "09. system",
        },
    },
    media_play_pause = {
        scope = "global",
        modifiers = {},
        key = "XF86AudioPlay",
        on_press = "media_play_pause",
        description = "toggle play/pause",
        group = "05. media",
    },
    media_next = {
        scope = "global",
        modifiers = {},
        key = "XF86AudioNext",
        on_press = "media_next",
        description = "next media item",
        group = "05. media",
    },
    media_prev = {
        scope = "global",
        modifiers = {},
        key = "XF86AudioPrev",
        on_press = "media_prev",
        description = "prev media item",
        group = "05. media",
    },
    volume_up = {
        scope = "global",
        modifiers = {},
        key = "XF86AudioRaiseVolume",
        on_press = "volume_up",
        description = "volume up",
        group = "05. media",
    },
    volume_down = {
        scope = "global",
        modifiers = {},
        key = "XF86AudioLowerVolume",
        on_press = "volume_down",
        description = "volume down",
        group = "05. media",
    },
    toggle_mute = {
        scope = "global",
        modifiers = {},
        key = "XF86AudioMute",
        on_press = "toggle_mute",
        description = "toggle mute",
        group = "05. media",
    },
    brightness_up = {
        scope = "global",
        modifiers = {},
        key = "XF86MonBrightnessUp",
        on_press = "brightness_up",
        description = "brightness up",
        group = "05. media",
    },
    brightness_down = {
        scope = "global",
        modifiers = {},
        key = "XF86MonBrightnessDown",
        on_press = "brightness_down",
        description = "brightness down",
        group = "05. media",
    },
    brightness_off = {
        scope = "global",
        modifiers = {},
        key = "XF86Display",
        on_press = "brightness_off",
        description = "display off",
        group = "05. media",
    },
    show_help = {
        scope = "global",
        modifiers = { "modkey" },
        key = "s",
        on_press = "show_help",
        description = "show help",
        group = "08. awesomewm",
    },
    reload_awesome = {
        {
            scope = "global",
            modifiers = { "altkey", "ctrlkey" },
            key = "r",
            on_press = "awesome_reload",
            description = "reload awesome",
            group = "08. awesomewm",
        },
        {
            scope = "global",
            modifiers = { "modkey", "ctrlkey" },
            key = "r",
            on_press = "awesome_restart",
            description = "reload awesome",
            group = "08. awesomewm",
        },
    },
    quit_awesome = {
        scope = "global",
        modifiers = { "modkey", "shiftkey" },
        key = "q",
        on_press = "awesome_quit",
        description = "quit awesome",
        group = "08. awesomewm",
    },
    toggle_notifications = {
        scope = "global",
        modifiers = { "modkey", "altkey", "ctrlkey" },
        key = "End",
        on_press = "toggle_notifications",
        description = "toggle notifications",
        group = "09. system",
    },
    kill_client = {
        scope = "client",
        modifiers = { "modkey", "shiftkey" },
        key = "c",
        on_press = "kill_client",
        description = "close",
        group = "01. window",
    },
    toggle_floating = {
        scope = "client",
        modifiers = { "modkey", "ctrlkey" },
        key = "space",
        on_press = "toggle_floating",
        description = "toggle floating",
        group = "01. window",
    },
    move_to_screen = {
        scope = "client",
        modifiers = { "modkey" },
        key = "o",
        on_press = "move_to_screen",
        description = "move to screen",
        group = "01. window",
    },
    move_to_left_screen = {
        scope = "client",
        modifiers = { "modkey", "altkey" },
        key = "Left",
        on_press = "move_to_left_screen",
        description = "move to left screen",
        group = "01. window",
    },
    move_to_right_screen = {
        scope = "client",
        modifiers = { "modkey", "altkey" },
        key = "Right",
        on_press = "move_to_right_screen",
        description = "move to right screen",
        group = "01. window",
    },
    toggle_titlebar = {
        scope = "client",
        modifiers = { "modkey", "ctrlkey" },
        key = "t",
        on_press = "toggle_titlebar",
        description = "toggle titlebar",
        group = "01. window",
    },
    minimize_client = {
        scope = "client",
        modifiers = { "modkey" },
        key = "n",
        on_press = "minimize_client",
        description = "minimize",
        group = "01. window",
    },
    maximize_client = {
        scope = "client",
        modifiers = { "modkey" },
        key = "m",
        on_press = "maximize_client",
        description = "maximize",
        group = "01. window",
    },
}

return M
