local M = {
    global_order = {
        "window_jump_to_urgent_client",
        "window_restore_minimized_program",
        "window_focus_next_by_index",
        "window_focus_previous_by_index",
        "window_swap_with_left_client",
        "window_swap_with_right_client",
        "window_swap_with_upper_client",
        "window_swap_with_lower_client",
        "window_focus_down",
        "window_focus_up",
        "window_focus_left",
        "window_focus_right",
        "desktop_view_previous",
        "desktop_view_next",
        "desktop_go_back",
        "layout_select_next_layout",
        "layout_select_prev_layout",
        "layout_increment_useless_gaps",
        "layout_decrement_useless_gaps",
        "programs_show_media_popup",
        "programs_show_notification_popup",
        "programs_show_bluetooth_popup",
        "programs_show_network_popup",
        "programs_show_powerprofiles_popup",
        "programs_show_calendar",
        "programs_lxrunner",
        "programs_launcher",
        "programs_terminal",
        "programs_file_browser",
        "programs_screenshot_region",
        "programs_screenshot_desktop",
        "programs_screenshot_window",
        "programs_start_awesome_on_tv",
        "programs_lock_screen_alt_ctrl_l",
        "programs_lock_screen_mod_alt_f12",
        "media_toggle_play_pause",
        "media_next_media_item",
        "media_prev_media_item",
        "media_volume_up",
        "media_volume_down",
        "media_toggle_mute",
        "media_brightness_up",
        "media_brightness_down",
        "media_display_off",
        "awesome_show_help",
        "awesome_reload_alt_ctrl_r",
        "awesome_reload_mod_ctrl_r",
        "awesome_quit",
        "system_toggle_notifications",
        "system_lock_screen",
    },
    global = {
        programs_quake_terminal = {
            modifiers = { "modkey" },
            key = "dead_circumflex",
            on_press = "toggle_quake",
            description = "quake terminal",
            group = "04. programs",
        },
        window_jump_to_urgent_client = {
            modifiers = { "modkey" },
            key = "u",
            on_press = "jump_to_urgent_client",
            description = "jump to urgent client",
            group = "01. window",
        },
        window_restore_minimized_program = {
            modifiers = { "modkey", "ctrlkey" },
            key = "n",
            on_press = "restore_minimized",
            description = "restore minimized program",
            group = "01. window",
        },
        window_focus_next_by_index = {
            modifiers = { "modkey" },
            key = "Tab",
            on_press = "cycle_focus",
            description = "focus next by index",
            group = "01. window",
        },
        window_focus_previous_by_index = {
            modifiers = { "modkey", "shiftkey" },
            key = "Tab",
            on_press = "cycle_focus",
            description = "focus previous by index",
            group = "01. window",
        },
        window_swap_with_left_client = {
            modifiers = { "modkey", "ctrlkey" },
            key = "Right",
            on_press = "swap_right",
            description = "swap with left client",
            group = "01. window",
        },
        window_swap_with_right_client = {
            modifiers = { "modkey", "ctrlkey" },
            key = "Left",
            on_press = "swap_left",
            description = "swap with right client",
            group = "01. window",
        },
        window_swap_with_upper_client = {
            modifiers = { "modkey", "ctrlkey" },
            key = "Up",
            on_press = "swap_up",
            description = "swap with upper client",
            group = "01. window",
        },
        window_swap_with_lower_client = {
            modifiers = { "modkey", "ctrlkey" },
            key = "Down",
            on_press = "swap_down",
            description = "swap with lower client",
            group = "01. window",
        },
        window_focus_down = {
            modifiers = { "modkey" },
            key = "Down",
            on_press = "focus_down",
            description = "focus down",
            group = "01. window",
        },
        window_focus_up = {
            modifiers = { "modkey" },
            key = "Up",
            on_press = "focus_up",
            description = "focus up",
            group = "01. window",
        },
        window_focus_left = {
            modifiers = { "modkey" },
            key = "Left",
            on_press = "focus_left",
            description = "focus left",
            group = "01. window",
        },
        window_focus_right = {
            modifiers = { "modkey" },
            key = "Right",
            on_press = "focus_right",
            description = "focus right",
            group = "01. window",
        },
        desktop_view_previous = {
            modifiers = { "altkey", "ctrlkey" },
            key = "Left",
            on_press = "view_previous_tag",
            description = "view previous",
            group = "02. desktop",
        },
        desktop_view_next = {
            modifiers = { "altkey", "ctrlkey" },
            key = "Right",
            on_press = "view_next_tag",
            description = "view next",
            group = "02. desktop",
        },
        desktop_go_back = {
            modifiers = { "modkey", "altkey" },
            key = "Escape",
            on_press = "restore_tag_history",
            description = "go back",
            group = "02. desktop",
        },
        layout_select_next_layout = {
            modifiers = { "modkey" },
            key = "space",
            on_press = "next_layout",
            description = "select next layout",
            group = "03. layout",
        },
        layout_select_prev_layout = {
            modifiers = { "modkey", "shiftkey" },
            key = "space",
            on_press = "prev_layout",
            description = "select prev layout",
            group = "03. layout",
        },
        layout_increment_useless_gaps = {
            modifiers = { "modkey", "ctrlkey" },
            key = "+",
            on_press = "grow_gaps",
            description = "increment useless gaps",
            group = "03. layout",
        },
        layout_decrement_useless_gaps = {
            modifiers = { "modkey", "ctrlkey" },
            key = "-",
            on_press = "shrink_gaps",
            description = "decrement useless gaps",
            group = "03. layout",
        },
        programs_show_media_popup = {
            modifiers = { "modkey" },
            key = "Prior",
            on_press = "show_media_popup",
            description = "show media popup",
            group = "04. programs",
        },
        programs_show_notification_popup = {
            modifiers = { "modkey" },
            key = "Next",
            on_press = "show_notification_popup",
            description = "show notification popup",
            group = "04. programs",
        },
        programs_show_bluetooth_popup = {
            modifiers = { "modkey" },
            key = "F10",
            on_press = "show_bluetooth_popup",
            description = "show bluetooth popup",
            group = "04. programs",
        },
        programs_show_network_popup = {
            modifiers = { "modkey" },
            key = "F11",
            on_press = "show_network_popup",
            description = "show network popup",
            group = "04. programs",
        },
        programs_show_powerprofiles_popup = {
            modifiers = { "modkey" },
            key = "F12",
            on_press = "show_powerprofiles_popup",
            description = "show power profiles popup",
            group = "04. programs",
        },
        programs_show_calendar = {
            modifiers = { "modkey" },
            key = "c",
            on_press = "show_calendar",
            description = "show calendar",
            group = "04. programs",
        },
        programs_lxrunner = {
            modifiers = { "altkey" },
            key = "F2",
            on_press = "toggle_lxrunner",
            description = "lxrunner",
            group = "04. programs",
        },
        programs_launcher = {
            modifiers = { "altkey" },
            key = "F3",
            on_press = "open_launcher",
            description = "launcher",
            group = "04. programs",
        },
        programs_terminal = {
            modifiers = { "modkey" },
            key = "q",
            on_press = "open_terminal",
            description = "terminal",
            group = "04. programs",
        },
        programs_file_browser = {
            modifiers = { "modkey" },
            key = "e",
            on_press = "open_file_browser",
            description = "file browser",
            group = "04. programs",
        },
        programs_screenshot_region = {
            modifiers = { "modkey" },
            key = "p",
            on_press = "screenshot_region",
            description = "screenshot of region",
            group = "04. programs",
        },
        programs_screenshot_desktop = {
            modifiers = { "altkey", "ctrlkey" },
            key = "p",
            on_press = "screenshot_desktop",
            description = "screenshot of desktop",
            group = "04. programs",
        },
        programs_screenshot_window = {
            modifiers = { "modkey", "ctrlkey" },
            key = "p",
            on_press = "screenshot_window",
            description = "screenshot of window",
            group = "04. programs",
        },
        programs_start_awesome_on_tv = {
            modifiers = { "modkey", "altkey" },
            key = "t",
            on_press = "start_awesome_on_tv",
            description = "start awesome on TV",
            group = "04. programs",
        },
        programs_lock_screen_alt_ctrl_l = {
            modifiers = { "altkey", "ctrlkey" },
            key = "l",
            on_press = "lock_screen",
            description = "lock screen",
            group = "04. programs",
        },
        programs_lock_screen_mod_alt_f12 = {
            modifiers = { "modkey", "altkey" },
            key = "F12",
            on_press = "lock_screen",
            description = "lock screen",
            group = "04. programs",
        },
        media_toggle_play_pause = {
            modifiers = {},
            key = "XF86AudioPlay",
            on_press = "media_play_pause",
            description = "toggle play/pause",
            group = "05. media",
        },
        media_next_media_item = {
            modifiers = {},
            key = "XF86AudioNext",
            on_press = "media_next",
            description = "next media item",
            group = "05. media",
        },
        media_prev_media_item = {
            modifiers = {},
            key = "XF86AudioPrev",
            on_press = "media_prev",
            description = "prev media item",
            group = "05. media",
        },
        media_volume_up = {
            modifiers = {},
            key = "XF86AudioRaiseVolume",
            on_press = "volume_up",
            description = "volume up",
            group = "05. media",
        },
        media_volume_down = {
            modifiers = {},
            key = "XF86AudioLowerVolume",
            on_press = "volume_down",
            description = "volume down",
            group = "05. media",
        },
        media_toggle_mute = {
            modifiers = {},
            key = "XF86AudioMute",
            on_press = "toggle_mute",
            description = "toggle mute",
            group = "05. media",
        },
        media_brightness_up = {
            modifiers = {},
            key = "XF86MonBrightnessUp",
            on_press = "brightness_up",
            description = "brightness up",
            group = "05. media",
        },
        media_brightness_down = {
            modifiers = {},
            key = "XF86MonBrightnessDown",
            on_press = "brightness_down",
            description = "brightness down",
            group = "05. media",
        },
        media_display_off = {
            modifiers = {},
            key = "XF86Display",
            on_press = "brightness_off",
            description = "display off",
            group = "05. media",
        },
        awesome_show_help = {
            modifiers = { "modkey" },
            key = "s",
            on_press = "show_help",
            description = "show help",
            group = "08. awesomewm",
        },
        awesome_reload_alt_ctrl_r = {
            modifiers = { "altkey", "ctrlkey" },
            key = "r",
            on_press = "awesome_reload",
            description = "reload awesome",
            group = "08. awesomewm",
        },
        awesome_reload_mod_ctrl_r = {
            modifiers = { "modkey", "ctrlkey" },
            key = "r",
            on_press = "awesome_restart",
            description = "reload awesome",
            group = "08. awesomewm",
        },
        awesome_quit = {
            modifiers = { "modkey", "shiftkey" },
            key = "q",
            on_press = "awesome_quit",
            description = "quit awesome",
            group = "08. awesomewm",
        },
        system_toggle_notifications = {
            modifiers = { "modkey", "altkey", "ctrlkey" },
            key = "End",
            on_press = "toggle_notifications",
            description = "toggle notifications",
            group = "09. system",
        },
        system_lock_screen = {
            modifiers = { "modkey", "altkey", "ctrlkey" },
            key = "Delete",
            on_press = "lock_screen",
            description = "lock screen",
            group = "09. system",
        },
    },
    client_order = {
        "client_close",
        "client_toggle_floating",
        "client_move_to_screen",
        "client_move_to_left_screen",
        "client_move_to_right_screen",
        "client_toggle_titlebar",
        "client_minimize",
        "client_maximize",
    },
    client = {
        client_close = {
            modifiers = { "modkey", "shiftkey" },
            key = "c",
            on_press = "kill_client",
            description = "close",
            group = "01. window",
        },
        client_toggle_floating = {
            modifiers = { "modkey", "ctrlkey" },
            key = "space",
            on_press = "toggle_floating",
            description = "toggle floating",
            group = "01. window",
        },
        client_move_to_screen = {
            modifiers = { "modkey" },
            key = "o",
            on_press = "move_to_screen",
            description = "move to screen",
            group = "01. window",
        },
        client_move_to_left_screen = {
            modifiers = { "modkey", "altkey" },
            key = "Left",
            on_press = "move_to_left_screen",
            description = "move to left screen",
            group = "01. window",
        },
        client_move_to_right_screen = {
            modifiers = { "modkey", "altkey" },
            key = "Right",
            on_press = "move_to_right_screen",
            description = "move to right screen",
            group = "01. window",
        },
        client_toggle_titlebar = {
            modifiers = { "modkey", "ctrlkey" },
            key = "t",
            on_press = "toggle_titlebar",
            description = "toggle titlebar",
            group = "01. window",
        },
        client_minimize = {
            modifiers = { "modkey" },
            key = "n",
            on_press = "minimize_client",
            description = "minimize",
            group = "01. window",
        },
        client_maximize = {
            modifiers = { "modkey" },
            key = "m",
            on_press = "maximize_client",
            description = "maximize",
            group = "01. window",
        },
    },
}

return M
