local M = {}

function M.build()
    local palette = {
        accent = "#dca3a3",
        urgent = "#cc9393",
        fg = "#dcdccc",
        bg = "#3f3f3f",
        bg_alt = "#4f4f4f",
        bg_dark = "#2b2b2b",
        border = "#6f6f6f",
        black = "#1f1f1f",
        hover = "#5f5f5f",
        hover_strong = "#7f9f7f",
        muted = "#9fafaf",
        meta = "#bfbfbf",
        low = "#8cd0d3",
        normal = "#f0dfaf",
        critical = "#cc9393",
    }

    local roles = {
        panel_bg = palette.bg,
        panel_bg_active = palette.bg_alt,
        panel_bg_muted = palette.bg_dark,
        panel_border = palette.border,
        text = palette.fg,
        text_accent = palette.accent,
        text_urgent = palette.urgent,
        text_muted = palette.muted,
        text_meta = palette.meta,
        raised_bg = palette.hover,
        hover_bg = palette.hover_strong,
        notification_bg = palette.black,
        bar_bg = palette.bg_dark,
        bar_fg = palette.fg,
    }

    local fonts = {
        base = "Hack Nerd Font Mono 9",
        icon = "Hack Nerd Font Mono 10",
        icon_large = "Hack Nerd Font Mono 11",
        icon_very_large = "Hack Nerd Font Mono 12",
        notify_widget = "Hack Nerd Font Mono 9",
    }

    return {
        fonts = fonts,
        theme = {
            fg_normal = roles.text,
            fg_focus = roles.text_accent,
            fg_minimize = roles.text_muted,
            fg_urgent = roles.text_urgent,
            bg_normal = roles.panel_bg,
            bg_focus = roles.panel_bg,
            bg_minimize = roles.panel_bg_muted,
            bg_systray = roles.panel_bg_active,
            bg_urgent = roles.panel_bg_active,
            border_normal = roles.notification_bg,
            border_focus = roles.panel_border,

            tasklist_bg_normal = roles.panel_bg,
            tasklist_bg_focus = roles.panel_bg_active,
            tasklist_fg_normal = roles.text,
            tasklist_fg_focus = roles.text_accent,
            taglist_bg_normal = roles.panel_bg,
            taglist_bg_focus = roles.panel_bg_active,
            taglist_fg_normal = roles.text,
            taglist_fg_focus = roles.text_accent,

            notification_bg = roles.notification_bg,
            notification_fg = roles.text,
            notification_border_color = roles.panel_border,

            lxmedia_bg_hover = roles.panel_bg,
            lxmedia_popup_bg = roles.panel_bg,
            lxmedia_button_bg = roles.raised_bg,
            lxmedia_button_hover = roles.hover_bg,
            lxmedia_bar_bg = roles.bar_bg,
            lxmedia_bar_fg = roles.bar_fg,
            lxmedia_mic_bar_bg = roles.bar_bg,
            lxmedia_mic_bar_fg = palette.critical,
            lxmedia_osd_bar_bg = roles.bar_bg,
            lxmedia_osd_bar_fg = roles.bar_fg,
            lxmedia_widget_fg = roles.text,
            lxmedia_widget_muted_fg = roles.text_muted,
            lxmedia_widget_mic_fg = palette.critical,
            lxmedia_widget_mic_muted_fg = roles.text_muted,
            lxmedia_selected_border = roles.text_accent,

            lxnotify_widget_fg = roles.text,
            lxnotify_widget_suspended_fg = roles.text_muted,
            lxnotify_widget_hover_bg = roles.panel_bg,
            lxnotify_widget_press_bg = roles.hover_bg,
            lxnotify_popup_bg = roles.panel_bg,
            lxnotify_notification_card_bg = roles.raised_bg,
            lxnotify_notification_meta_fg = roles.text_meta,
            lxnotify_card_hover_bg = roles.hover_bg,
            lxnotify_button_bg = roles.raised_bg,
            lxnotify_button_hover = roles.hover_bg,
            lxnotify_selected_bg = roles.text_accent,
            lxnotify_urgency_low_fg = palette.low,
            lxnotify_urgency_normal_fg = palette.normal,
            lxnotify_urgency_critical_fg = palette.critical,

            lxdisplay_widget_fg = roles.text,
            lxdisplay_widget_suspended_fg = roles.text_muted,
            lxdisplay_bar_bg = roles.bar_bg,
            lxdisplay_bar_fg = roles.bar_fg,
            lxdisplay_popup_bg = roles.panel_bg,
            lxdisplay_button_bg = roles.raised_bg,
            lxdisplay_button_hover = roles.hover_bg,
            lxdisplay_selected_bg = roles.text_accent,
            lxdisplay_meta_fg = roles.text_meta,
            lxdisplay_optional_fg = palette.critical,
            lxdisplay_widget_hover_bg = roles.panel_bg,
            lxdisplay_widget_press_bg = roles.hover_bg,
            lxdisplay_osd_bar_bg = roles.bar_bg,
            lxdisplay_osd_bar_fg = roles.bar_fg,

            lxbluetooth_widget_fg = roles.text,
            lxbluetooth_widget_disabled_fg = roles.text_muted,
            lxbluetooth_widget_hover_bg = roles.panel_bg,
            lxbluetooth_widget_press_bg = roles.hover_bg,
            lxbluetooth_popup_bg = roles.panel_bg,
            lxbluetooth_button_hover = roles.hover_bg,
            lxbluetooth_selected_bg = roles.text_accent,
            lxbluetooth_meta_fg = roles.text_meta,

            lxnetwork_widget_fg = roles.text,
            lxnetwork_widget_disabled_fg = roles.text_muted,
            lxnetwork_widget_hover_bg = roles.panel_bg,
            lxnetwork_widget_press_bg = roles.hover_bg,
            lxnetwork_popup_bg = roles.panel_bg,
            lxnetwork_button_hover = roles.hover_bg,
            lxnetwork_selected_bg = roles.text_accent,
            lxnetwork_meta_fg = roles.text_meta,
            lxnetwork_widget_vpn_fg = palette.critical,
            lxnetwork_signal_bar_bg = roles.bar_bg,
            lxnetwork_signal_bar_fg = roles.bar_fg,

            lxpower_widget_fg = roles.text,
            lxpower_widget_hover_bg = roles.panel_bg,
            lxpower_widget_press_bg = roles.hover_bg,
            lxpower_popup_bg = roles.panel_bg,
            lxpower_button_hover = roles.hover_bg,
            lxpower_selected_bg = roles.text_accent,
            lxpower_meta_fg = roles.text_meta,
            lxpower_profile_fg_powersave = roles.text_muted,
            lxpower_profile_fg_balanced = roles.text,
            lxpower_profile_fg_performance = palette.critical,

            lxsecrets_widget_fg = roles.text,
            lxsecrets_widget_suspended_fg = roles.text_muted,
            lxsecrets_widget_attention_fg = palette.critical,
            lxsecrets_widget_hover_bg = roles.panel_bg,
            lxsecrets_widget_press_bg = roles.hover_bg,
            lxsecrets_popup_bg = roles.panel_bg,
            lxsecrets_button_bg = roles.raised_bg,
            lxsecrets_button_hover = roles.hover_bg,
            lxsecrets_selected_bg = roles.text_accent,
            lxsecrets_meta_fg = roles.text_meta,

            lxrunner_bg = roles.panel_bg,
            lxrunner_border_color = roles.panel_border,
            lxrunner_input_bg = roles.panel_bg_muted,
            lxrunner_input_fg = roles.text,
            lxrunner_prompt_fg = roles.text_accent,
            lxrunner_row_bg = roles.panel_bg,
            lxrunner_row_fg = roles.text_meta,
            lxrunner_row_selected_bg = roles.raised_bg,
            lxrunner_row_selected_fg = roles.text,
        },
    }
end

return M
